# Generated by Django 4.2.1 on 2024-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
