# Generated by Django 4.2.1 on 2025-01-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='animals.tagpost'),
        ),
    ]
